# Załadowanie pliku do pamięci RAM
preload = /home/kxox/Downloads/wallpaper.jpg

# Ustawienie na jedynym monitorze
# Puste miejsce przed przecinkiem oznacza "wszystkie monitory"
wallpaper = ,/home/kxox/Downloads/wallpaper.jpg

# Wyłączenie tekstu na dole ekranu
splash = false
