general {
  #  no_fade_in = false
    grace = 0
    disable_loading = true
}

background {
    monitor =
      path =           /home/kxox/Downloads/arch-linux-cube.jpg 
    color = rgba(25, 20, 20, 1.0)
    blur_passes = 0 # 0 wyłącza rozmycie
    blur_size = 7
    noise = 0.0117
    contrast = 0.8916
    brightness = 0.8172
    vignette = 0.1
    vignette_intensity = 0.5
}

# CZAS
label {
    monitor =
    text = $TIME
    color = rgba(200, 200, 200, 1.0)
    font_size = 64
    font_family = Noto Sans
    position = 0, 80
    halign = center
    valign = center
}

# USER
label {
    monitor =
    text = Welcome, $USER
    color = rgba(200, 200, 200, 1.0)
    font_size = 20
    font_family = Noto Sans
    position = 0, 0
    halign = center
    valign = center
    capsloc
}


label {
    monitor =
    # Wykonuje skrypt co 60 sekund (60000 ms)
  text = cmd[update:60000] bash /home/kxox/Scripts/battery.sh
    
    color = rgba(200, 200, 200, 1.0)
    font_size = 20
    font_family = JetBrainsMono Nerd Font 
    
    # Pozycja w prawym górnym rogu
    position = -20, -20
    halign = right
    valign = top
}



#CAPSLOCK CHECKER
label {
    
text = $LAYOUT
text = cmd[update:100] echo "$(cat /sys/class/leds/input*::capslock/brightness | grep -q '1' && echo 'capslock is on' || echo '')"

color = rgb(255, 165, 0)
font_size = 12
font_family = Noto Sans Light

position = 0,-30
halign = center
valign = center 

    
        
}


# POLE HASŁA
input-field {
    monitor =
    size = 200, 50
    shadow_passes = 1
    outline_thickness = 3
    dots_size = 0.33
    dots_spacing = 0.15
    dots_center = true
    outer_color = rgb(151515)
    inner_color = rgba(200,200,200,0.5)
    font_color = rgb(10, 10, 10)
    fade_on_empty = true
    placeholder_text = 
    hide_input = false
    position = 0, -80
    halign = center
    valign = center
    
    capslock_color = rgb(255, 165, 0)
    text = <span foreground="##ffaa00">Caps Lock ON</span>
    
    check_color = rgb(151515)
    
    fail_color = rgb(255,0,0)
    fail_transition = 0
    fail_text = <b>WRONG PASSWORD</b>
}
